# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Develost: projects collector of Massimiliano Bernabé'
tagline:          'A Metro theme for Jekyll'
description:      'A Sample blog using Jekyll Metro'
#url:              'http://192.168.1.11:4000'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'Massimiliano Bernabé'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       'https://www.facebook.com/pages/develostcom/1400737306913750'
flickr:
github:         'https://twitter.com/develost_com'
gplus:
instagram:
pinterest:
linkedin:       'https://www.linkedin.com/in/massimilianobernabe'
rss:
stackoverflow:  'http://stackoverflow.com/users/4759300/develost'
twitter:        'https://twitter.com/develost_com'

# Google Analytics
gahandler: 'UA-XXXX-X'


#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
